# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTU2YWNlZjhkNjIyNWE5NGMzNjVkNzY1ZmY1ZGE2ZWE1NTFlMmNiN2M2Zjc2NTI1MTYzODA3M2ZiMzdjOTIxMzEwZWVhODcwN2Y4NTM2NzcwMDA1ZTBjZjMzZjFmMWE3NDI2YmYyZTllOTczZmEyY2FmOGQwMTExZTUwOTAwZmY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
